apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prd
spec:
  containers:
    - image: kubia:v0.1
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
