apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
spec:
  containers:
    - name: html-generator
      image: registry.cn-shanghai.aliyuncs.com/reuity/fortune
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - name: web-server
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/index.html
          readOnly: yes
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir: {}
