apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
    - image: kubia-unhealthy:v0.1
      name: kubia
      livenessProbe:
        httpGet:
          path: /
          port: 8080
